### ISSUE TITLE
11funkcije: vhod izven domene

### ISSUE THREAD

**Issue by sijanec** [nik1178/APSTester#3]
https://github.com/nik1178/APSTester/blob/f80411f330e907d359a00fa69f0acfe74909cfbf/inputGeneration.py#L1184

Generira b_i=100000000000, toda za b_i velja omejitev vhoda b_i <= 1000000000.

https://ucilnica.fri.uni-lj.si/mod/assign/view.php?id=53076

**Comment by nik1178** [comment]
Zmanjšano na 10^9, hvala!
